inherit_from: .rubocop_todo.yml
require: rubocop-rspec

Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/GuardClause:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Lambda:
  Enabled: false

Style/AndOr:
  EnforcedStyle: always

Style/Alias:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%W': '()'
    '%i': '()'

Style/SymbolArray:
  EnforcedStyle: percent

Style/SpecialGlobalVars:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 1000

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/zssn/docs/**/*'

Metrics/MethodLength:
  Max: 1000

Metrics/LineLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/PerceivedComplexity:
  Max: 14

Naming/VariableNumber:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

Rails:
  Enabled: true

RSpec/NamedSubject:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/api/v1/items_controller_spec.rb'
    - 'spec/models/item_spec.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/trader_service.rb'

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'